apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-service-catalog-removed
  annotations:
    release.openshift.io/delete: "true"
    openshift.io/node-selector: ""
